= Silo V2 edit TET

== Summary

Silo V2 merupakan sistem yang berfungsi untuk menangani penjualan produk fisik seperti ponsel dan mobile modem beserta _starter pack_ (kartu perdana) atau _bundling_ paket data.
Pada sistem ini, _request_ dari _partner merchant_ akan disimpan sementara (_inventory_), lalu akan didistribusikan ke _customer_.

Terdapat 4 aktor yang terlibat dalam sistem Silo V2, yaitu:

. Partner Merchant
. Silo (Sistem)
. Telco
. Silo (Sepulsa Ops)

== Anggota Tim Silo V2

|===
| *Role* | *Team* | *Name*

| Product Owner
| JackRabbit
| Aryo Indrasmoro

| Development Manager
| JackRabbit
| Aryo Indrasmoro

| Lead Developer
| JackRabbit
| Ananto Eko Hendarto

| Lead Quality Engineer
| Otter
| Marco Ichwan Bosch

| Lead System Analyst
| Pelican
| Gabriel Stevano
|===

== Informasi Teknis

<<Silo-V2/system-url-silov2.adoc#, System URL>>

<<Silo-V2/arsitektur-silov2.adoc#, Architecture>>

<<Silo-V2/technology-silov2.adoc#, Technology>>

<<Silo-V2/environment-silov2.adoc#, Environment>>

<<Silo-V2/database-documentation-silov2.adoc#, Database>>

<<Silo-V2/release-deployment-silov2.adoc#, Release and Deployment>>

== Onboarding Information

<<Silo-V2/developer-onboarding-silov2.adoc#, Developer Onboarding>>

<<Silo-V2/development-silov2.adoc#, Development>>

<<Silo-V2/convention-silov2.adoc#, Naming Convention>>

== Documentation

https://github.com/sepulsa/silo2/releases[Release Note]

https://silo.sumpahpalapa.com/admin/apidoc[API Documentation]

<<Silo-V2/problem-and-troubleshoot-silov2.adoc#, Problem and Troubleshoot>>
